
name: Node.js Package

on:
  release:
    types: [ created ]

jobs:
  publish-npm:
    name: Publish on npm
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/

    - name: Install packages
      run: npm ci

    - name: Build
      run: npm run-script build

    - name: Publish release
      run: npm publish --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
